### ISSUE TITLE
Crop parameters point outside of the image error

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/iiif-image-server#1]
If you go here: https://data.nhm.ac.uk/iiif_images/vfactor:L014163636.jpg/8192,8192,5979,6641/748,/0/default.jpg

You get a 500 and this in the logs:

```
Traceback (most recent call last):
  File "/usr/lib/iiif_image_server/iiif-image-server/venv/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/usr/lib/iiif_image_server/iiif-image-server/iiif/web.py", line 70, in get
    await self.dispatcher.submit(task)
  File "/usr/lib/iiif_image_server/iiif-image-server/iiif/processing.py", line 325, in submit
    await self.output_paths[task.output_path]
ValueError: Crop parameters point outside of the image
```

This is presumably erroring in jpegtran.

Initial thoughts are that we need to apply a ceiling to the width/height of crops so that they don't fall outside of the boundaries of the actual image. Need to check that this is a valid IIIF request though (it's coming from an openseadragon instance though so I would assume it is).

**Comment by jrdh** [comment]
Fixed during latest changes: https://data.nhm.ac.uk/media/vfactor:L014163636.jpg/8192,8192,5979,6641/748,/0/default.jpg
